// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// GetSomeIdsOpsParamsBody get some ids ops params body
// swagger:model getSomeIdsOpsParamsBody
type GetSomeIdsOpsParamsBody struct {

	// some ids
	SomeIds IDList `json:"someIds"`
}

// Validate validates this get some ids ops params body
func (m *GetSomeIdsOpsParamsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *GetSomeIdsOpsParamsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetSomeIdsOpsParamsBody) UnmarshalBinary(b []byte) error {
	var res GetSomeIdsOpsParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
