// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetSomeIdsOpsOKCode is the HTTP code returned for type GetSomeIdsOpsOK
const GetSomeIdsOpsOKCode int = 200

/*GetSomeIdsOpsOK get some ids ops o k

swagger:response getSomeIdsOpsOK
*/
type GetSomeIdsOpsOK struct {
}

// NewGetSomeIdsOpsOK creates GetSomeIdsOpsOK with default headers values
func NewGetSomeIdsOpsOK() *GetSomeIdsOpsOK {
	return &GetSomeIdsOpsOK{}
}

// WriteResponse to the client
func (o *GetSomeIdsOpsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
