// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/go-swagger/go-swagger/fixtures/bugs/1289/models"
)

// NewGetSomeIdsOpsParams creates a new GetSomeIdsOpsParams object
// with the default values initialized.
func NewGetSomeIdsOpsParams() GetSomeIdsOpsParams {
	var ()
	return GetSomeIdsOpsParams{}
}

// GetSomeIdsOpsParams contains all the bound params for the get some ids ops operation
// typically these are obtained from a http.Request
//
// swagger:parameters getSomeIdsOps
type GetSomeIdsOpsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	GetSomeIds *models.GetSomeIdsOpsParamsBody
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetSomeIdsOpsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.GetSomeIdsOpsParamsBody
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("getSomeIds", "body"))
			} else {
				res = append(res, errors.NewParseError("getSomeIds", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.GetSomeIds = &body
			}
		}

	} else {
		res = append(res, errors.Required("getSomeIds", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
