// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi issue-1289

    Schemes:
      http
    Host: localhost:8081
    BasePath: /api/v1
    Version: 1.0
    License: MIT

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
