// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "issue-1289",
    "license": {
      "name": "MIT"
    },
    "version": "1.0"
  },
  "host": "localhost:8081",
  "basePath": "/api/v1",
  "paths": {
    "/getSomeIds": {
      "get": {
        "operationId": "getSomeIdsOps",
        "parameters": [
          {
            "name": "getSomeIds",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "someIds": {
                  "$ref": "#/definitions/idList"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {}
        }
      }
    }
  },
  "definitions": {
    "idList": {
      "type": "array",
      "items": {
        "type": "number"
      }
    }
  }
}`))
}
